import { Target, Brain, TrendingUp, CheckCircle2 } from 'lucide-react'
import Lottie from 'lottie-react'
import thinking from '../../assets/animations/thinking.json'
import { motion } from 'framer-motion'
import ScrollAnimationWrapper from './ScrollAnimationWrapper'

const steps = [
  {
    icon: Target,
    title: 'Set Your Goals',
    description:
      'Tell us about your fitness objectives, dietary preferences, and lifestyle. Our AI analyzes your unique needs to create a personalized baseline.',
    iconBg: 'bg-primary/10 dark:bg-primary/20',
    iconColor: 'text-primary dark:text-teal-400',
  },
  {
    icon: Brain,
    title: 'Get AI-Powered Plans',
    description:
      "Receive custom meal plans generated by our advanced AI, perfectly balanced for your goals with recipes you'll actually enjoy.",
    iconBg: 'bg-primary/10 dark:bg-primary/20',
    iconColor: 'text-primary dark:text-teal-500',
  },
  {
    icon: TrendingUp,
    title: 'Track Your Progress & Results',
    description:
      "Monitor calories, macros, water intake, and more. Our intuitive dashboard makes it easy to see how you're progressing toward your goals.",
    iconBg: 'bg-primary/10 dark:bg-primary/20',
    iconColor: 'text-primary dark:text-emerald-400',
  },
]

export default function HowItWorks() {
  return (
    <section
      id="how-it-works"
      className="py-24 bg-gray-50 dark:bg-gray-900 relative overflow-hidden"
    >
      {/* Animated background elements */}
      <div className="absolute inset-0 pointer-events-none">
        <motion.div
          animate={{
            scale: [1, 1.2, 1],
            opacity: [0.3, 0.5, 0.3],
          }}
          transition={{
            duration: 8,
            repeat: Infinity,
            ease: 'easeInOut',
          }}
          className="absolute top-1/3 left-0 w-96 h-96 bg-primary dark:bg-teal-600/10 rounded-full blur-3xl"
        ></motion.div>
        <motion.div
          animate={{
            scale: [1, 1.3, 1],
            opacity: [0.2, 0.4, 0.2],
          }}
          transition={{
            duration: 10,
            repeat: Infinity,
            ease: 'easeInOut',
            delay: 1,
          }}
          className="absolute bottom-1/3 right-0 w-64 h-64 bg-primary dark:bg-emerald-600/10 rounded-full blur-3xl"
        ></motion.div>
      </div>

      <div className="max-w-5xl mx-auto px-6 relative z-10">
        {/* Section Header */}

        <div className="text-center mb-16">
          <div className="inline-flex items-center gap-2 px-4 py-2 bg-primary/10 text-primary dark:bg-teal-900/30 dark:text-teal-400 rounded-full mb-6">
            <span className="text-sm font-medium">Simple Process</span>
          </div>
          <h2 className="text-4xl lg:text-5xl font-bold text-textDark dark:text-white mb-4">
            How Nutriva Works
          </h2>
          <p className="text-xl text-textLight dark:text-gray-400 max-w-2xl mx-auto">
            Three simple steps to transform your nutrition and achieve your
            health goals
          </p>
        </div>

        {/* Steps Grid */}
        <div className="grid md:grid-cols-2 gap-12 items-center">
          {/* Animation Side */}

          <div className="flex justify-center items-center">
            <div className="w-full max-w-[500px]">
              <Lottie animationData={thinking} loop={true} />
            </div>
          </div>

          {/* Cards Side */}
          <div className="space-y-4">
            {steps.map((step, index) => {
              const Icon = step.icon
              return (
                <ScrollAnimationWrapper
                  key={index}
                  delay={index * 0.15}
                  direction="up"
                >
                  <div className="relative group">
                    {/* Card */}
                    <div className="bg-white dark:bg-gray-800 rounded-xl p-8 border border-gray-200 dark:border-gray-700 hover:border-primary dark:hover:border-teal-500 hover:shadow-lg dark:hover:shadow-teal-500/20 transition-all duration-300">
                      {/* Step Number and Icon */}
                      <div className="flex items-start justify-between mb-3">
                        <div
                          className={`w-14 h-14 ${step.iconBg} rounded-xl flex items-center justify-center`}
                        >
                          <Icon className={`w-7 h-7 ${step.iconColor}`} />
                        </div>
                        <div className="w-8 h-8 bg-primary/10 dark:bg-teal-900/30 rounded-full flex items-center justify-center">
                          <span className="text-sm font-bold text-textLight dark:text-gray-400">
                            {index + 1}
                          </span>
                        </div>
                      </div>

                      {/* Content */}
                      <h3 className="text-xl font-bold text-textDark dark:text-white mb-3">
                        {step.title}
                      </h3>
                      <p className="text-textLight dark:text-gray-400 leading-relaxed">
                        {step.description}
                      </p>
                    </div>
                  </div>
                </ScrollAnimationWrapper>
              )
            })}
          </div>
        </div>
      </div>
    </section>
  )
}
