import { Target, Brain, TrendingUp, CheckCircle2 } from 'lucide-react'
import Lottie from 'lottie-react'
import thinking from '../../assets/animations/thinking.json'

const steps = [
  {
    icon: Target,
    title: 'Set Your Goals',
    description:
      'Tell us about your fitness objectives, dietary preferences, and lifestyle. Our AI analyzes your unique needs to create a personalized baseline.',
    color: 'from-emerald-400 to-teal-600',
    iconBg: 'bg-emerald-100',
    iconColor: 'text-emerald-600',
  },
  {
    icon: Brain,
    title: 'Get AI-Powered Plans',
    description:
      "Receive custom meal plans generated by our advanced AI, perfectly balanced for your goals with recipes you'll actually enjoy.",
    color: 'from-teal-400 to-cyan-600',
    iconBg: 'bg-emerald-100',
    iconColor: 'text-teal-600',
  },
  {
    icon: TrendingUp,
    title: 'Track Your Progress & Results',
    description:
      "Monitor calories, macros, water intake, and more. Our intuitive dashboard makes it easy to see how you're progressing toward your goals.",
    color: 'from-cyan-400 to-blue-600',
    iconBg: 'bg-emerald-100',
    iconColor: 'text-cyan-600',
  },
]

export default function HowItWorks() {
  return (
    <section id="how-it-works" className="py-24 bg-gray-50">
      <div className="max-w-5xl mx-auto px-6">
        {/* Section Header */}
        <div className="text-center mb-16">
          <div className="inline-flex items-center gap-2 px-4 py-2 bg-emerald-100 text-emerald-700 rounded-full mb-6">
            <span className="text-sm font-medium">Simple Process</span>
          </div>
          <h2 className="text-4xl lg:text-5xl font-bold text-gray-900 mb-4">
            How Nutriva Works
          </h2>
          <p className="text-xl text-gray-600 max-w-2xl mx-auto">
            Four simple steps to transform your nutrition and achieve your
            health goals
          </p>
        </div>

        {/* Steps Grid */}
        <div className="grid md:grid-cols-2 gap-12 items-center">
          {/* Animation Side */}
          <div className="flex justify-center items-center">
            <div className="w-full max-w-[500px]">
              <Lottie animationData={thinking} loop={true} />
            </div>
          </div>

          {/* Cards Side */}
          <div className="space-y-4">
            {steps.map((step, index) => {
              const Icon = step.icon
              return (
                <div key={index} className="relative group">
                  {/* Card */}
                  <div className="bg-white rounded-xl p-8 border border-gray-200 hover:border-emerald-300 hover:shadow-lg transition-all duration-300">
                    {/* Step Number and Icon */}
                    <div className="flex items-start justify-between mb-3">
                      <div
                        className={`w-14 h-14 ${step.iconBg} rounded-xl flex items-center justify-center`}
                      >
                        <Icon className={`w-7 h-7 ${step.iconColor}`} />
                      </div>
                      <div className="w-8 h-8 bg-emerald-100 rounded-full flex items-center justify-center">
                        <span className="text-sm font-bold text-gray-600">
                          {index + 1}
                        </span>
                      </div>
                    </div>

                    {/* Content */}
                    <h3 className="text-xl font-bold text-gray-900 mb-3">
                      {step.title}
                    </h3>
                    <p className="text-gray-600 leading-relaxed">
                      {step.description}
                    </p>
                  </div>
                </div>
              )
            })}
          </div>
        </div>

        {/* Bottom CTA */}
        <div className="mt-16 text-center">
          <button className="px-8 py-4 bg-emerald-500 text-white rounded-xl hover:bg-emerald-600 transition-all shadow-lg shadow-emerald-500/30">
            Start Your Free Trial
          </button>
        </div>
      </div>
    </section>
  )
}
